// src/mockData.js
const mockReviews = [
    {
      id: 1,
      title: "서울의 숨겨진 맛집 탐방",
      description: "서울에서 발견한 작지만 훌륭한 레스토랑 리뷰입니다.",
      author: "김영호",
      date: "2024-12-01",
    },
    {
      id: 2,
      title: "파리의 예술적인 카페",
      description: "파리의 독특한 분위기를 자랑하는 카페 리뷰입니다.",
      author: "이민지",
      date: "2024-12-02",
    },
    {
      id: 3,
      title: "도쿄의 야경 명소 추천",
      description: "도쿄에서 꼭 가봐야 할 야경 스팟을 소개합니다.",
      author: "박준석",
      date: "2024-12-03",
    },
    {
      id: 4,
      title: "이탈리아 로마의 역사적인 명소",
      description: "로마 여행 중 방문한 고대 유적지 리뷰입니다.",
      author: "최은경",
      date: "2024-12-04",
    },
    {
      id: 5,
      title: "뉴욕의 브런치 레스토랑",
      description: "뉴욕에서 가장 인기 있는 브런치 장소를 리뷰했습니다.",
      author: "홍지수",
      date: "2024-12-05",
    },
    {
      id: 6,
      title: "런던의 히든 바",
      description: "런던에서 찾은 분위기 좋은 히든 바 리뷰입니다.",
      author: "김재민",
      date: "2024-12-06",
    },
    {
      id: 7,
      title: "시드니 오페라 하우스의 매력",
      description: "시드니의 랜드마크를 생생하게 담은 리뷰입니다.",
      author: "정하은",
      date: "2024-12-07",
    },
    {
      id: 8,
      title: "캐나다 밴쿠버의 자연 트레일",
      description: "밴쿠버에서 경험한 자연과 하이킹 코스를 소개합니다.",
      author: "오정민",
      date: "2024-12-08",
    },
    {
      id: 9,
      title: "홍콩의 야시장 투어",
      description: "홍콩 야시장에서 먹고 즐길 수 있는 것들을 리뷰했습니다.",
      author: "이유진",
      date: "2024-12-09",
    },
    {
      id: 10,
      title: "싱가포르의 야경 크루즈",
      description: "싱가포르에서 경험한 아름다운 크루즈 여행 리뷰입니다.",
      author: "권현우",
      date: "2024-12-10",
    },
    {
      id: 11,
      title: "타이완 타이페이의 거리 음식",
      description: "타이페이에서 맛본 길거리 음식 리뷰입니다.",
      author: "김나리",
      date: "2024-12-11",
    },
    {
      id: 12,
      title: "독일 뮌헨의 맥주 축제",
      description: "뮌헨에서 열린 옥토버페스트를 체험한 후기를 전합니다.",
      author: "박성훈",
      date: "2024-12-12",
    },
    {
      id: 13,
      title: "호주 멜버른의 아트 갤러리",
      description: "멜버른의 현대미술관을 방문한 경험을 리뷰했습니다.",
      author: "장현정",
      date: "2024-12-13",
    },
    {
      id: 14,
      title: "베트남 하노이의 커피 투어",
      description: "하노이에서 즐긴 다양한 커피 맛집을 리뷰합니다.",
      author: "최동민",
      date: "2024-12-14",
    },
    {
      id: 15,
      title: "네덜란드 암스테르담의 자전거 여행",
      description: "암스테르담에서 즐긴 자전거 여행 코스를 소개합니다.",
      author: "이서연",
      date: "2024-12-15",
    },
  ];
  
  export default mockReviews;
  